POST http://localhost:8080/api/v1/participants
Content-Type: application/json
Accept: application/json

{
  "eventToken": "6Kn67fw0",
  "personToken": "h-HNuIT1",
  "eventRoleSlug": "boss",
  "isPaid": true,
  "isInternal": true
}
###

GET http://localhost:8080/api/v1/participants?event_token=CVR9Rinx
###

GET http://localhost:8080/api/v1/participants?person_token=ugZj8o3M
###

GET http://localhost:8080/api/v1/participants/q5tXvaJg
###

PUT http://localhost:8080/api/v1/participants/q5tXvaJg
Content-Type: application/json

{
  "eventRoleSlug": "boss-2",
  "isPaid": true,
  "isInternal": true
}
###

DELETE http://localhost:8080/api/v1/participants?event_token=CVR9Rinx
###

DELETE http://localhost:8080/api/v1/participants/q5tXvaJg
###
