POST http://localhost:8080/api/v1/roles
Content-Type: application/json
Accept: application/json

{
  "name": "Boss Head Manager 13"
}
###

GET http://localhost:8080/api/v1/roles
###

GET http://localhost:8080/api/v1/roles/boss-Wpod
###

DELETE http://localhost:8080/api/v1/roles/boss-Wpod
###

DELETE http://localhost:8080/api/v1/roles
###




